#!/bin/bash -xe

make dist

amversion=`grep AM_INIT_AUTOMAKE configure.ac | cut -f2 -d" " | sed s/,//`

target=${WORKSPACE}/${amversion}-${BUILD_NUMBER}
rm -rf ${target}


rm -rf epicstcl-${amversion} 

tarball=epicstcl-${amversion}.tar.gz
version=${amversion}

echo ${tarball}


tar xzf ${tarball}
cd `basename ${tarball} .tar.gz`

./configure --prefix=${target}  --with-epics-rootdir=/usr/lib/epics
make clean all
make install


rm -rf `basename ${tarball} .tar.gz`
rm -rf ${target}

